events {}

http {

    upstream car_api {
        server car1:8080;
        server car2:8080;
        server car3:8080;
    }

    server {
        listen 80;

        location /cars {
            proxy_pass http://car_api;
        }
    }
}