events {}

http {

    upstream car_api {
        server car_service:8080;
    }

    upstream bike_api {
        server bike_service:8081;
    }

    server {
        listen 443 ssl;

        ssl_certificate /etc/nginx/ssl/server.crt;
        ssl_certificate_key /etc/nginx/ssl/server.key;

        ssl_protocols TLSv1.2 TLSv1.3;

        location /cars {
            proxy_pass http://car_api;
        }
    }

    server {
        listen 80;

        location /bikes {
            proxy_pass http://bike_api;
        }
    }
}