events {}

http {

    upstream car_api {
        server car_service:8080;
    }

    server {
        listen 443;

        server_name 65.0.85.195;

        ssl_certificate /etc/nginx/ssl/server.crt;
        ssl_certificate_key /etc/nginx/ssl/server.key;

        ssl_protocols TLSv1.2 TLSv1.3;

        location /cars {
            proxy_pass http://car_api;
        }
    }
}