events {}

http {

    upstream car_api {
        server car_service1:8080 weight=5;
        server car_service2:8080 weight=2;
        server car_service3:8080 weight=1;
    }

    server {
        listen 80;

        location /cars {
            proxy_pass http://car_api;
        }
    }
}