events {}

http {

    upstream car_api {
        server car_service:8080;
    }

    upstream bike_api {
        server bike_service:8081;
    }

    server {
        listen 80;

        # CAR APIs
        location /cars/ {
            proxy_pass http://car_api/;
        }

        location /cars {
            proxy_pass http://car_api;
        }

        # BIKE APIs
        location /bikes/ {
            proxy_pass http://bike_api/;
        }

        location /bikes {
            proxy_pass http://bike_api;
        }
    }
}