events {}

http {

    upstream car_app {
        server car_service:8080;
    }

    upstream bike_app {
        server bike_service:8081;
    }

    server {
        listen 80;

        # CAR APIs
        location /cars/ {
            proxy_pass http://car_app/;
        }

        location /cars {
            proxy_pass http://car_app;
        }

        # BIKE APIs
        location /bikes/ {
            proxy_pass http://bike_app/;
        }

        location /bikes {
            proxy_pass http://bike_app;
        }
    }
}